# Generated by Django 4.2.6 on 2024-03-22 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_role_alter_customuser_speciality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='birthday',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 22, 20, 40, 16, 825371), verbose_name='Дата создания'),
        ),
    ]
