# Generated by Django 4.2.6 on 2024-04-05 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_patient_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='birthday',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 5, 21, 5, 47, 746540), verbose_name='Дата создания'),
        ),
    ]
