# Generated by Django 4.2.9 on 2024-04-09 16:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_patient_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='birthday',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 9, 21, 56, 22, 431941), verbose_name='Дата создания'),
        ),
    ]
