# Generated by Django 4.2.6 on 2024-03-23 18:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0008_alter_patient_birthday'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanAxis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Ось снимка',
                'verbose_name_plural': 'Оси снимка',
            },
        ),
        migrations.CreateModel(
            name='TumorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория опухоли',
                'verbose_name_plural': 'Категории опухоли',
            },
        ),
        migrations.CreateModel(
            name='TumorStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Стадия опухоли',
                'verbose_name_plural': 'Стадии опухоли',
            },
        ),
        migrations.CreateModel(
            name='ScanRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_image', models.ImageField(blank=True, null=True, upload_to='scans/images/original/', verbose_name='Оригинальный снимок')),
                ('predicted_image', models.ImageField(blank=True, null=True, upload_to='scans/images/predicted/', verbose_name='Предсказанный снимок')),
                ('tumor_diagnosed', models.BooleanField(blank=True, null=True, verbose_name='Опухоль диагностирована')),
                ('tumor_predicted', models.BooleanField(blank=True, null=True, verbose_name='Опухоль предсказана')),
                ('predicted_probability', models.FloatField(default=0, verbose_name='Вероятность наличия')),
                ('data', models.JSONField(blank=True, null=True, verbose_name='Данные')),
                ('created_datetime', models.DateTimeField(default=datetime.datetime(2024, 3, 23, 23, 34, 18, 177248), verbose_name='Дата создания')),
                ('axis', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='scans_axis', to='scans.scanaxis', verbose_name='Ось')),
                ('by_user', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scans_author', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('final_tumor_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='scans_final_category', to='scans.tumorcategory', verbose_name='Финальная категория')),
                ('final_tumor_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='scans_final_stage', to='scans.tumorstage', verbose_name='Финальная стадия')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans_patient', to='users.patient', verbose_name='Пациент')),
                ('tumor_category_ai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='scans_tumor_ai_category', to='scans.tumorcategory', verbose_name='Категория опухоли (врач)')),
                ('tumor_category_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='scans_tumor_doc_category', to='scans.tumorcategory', verbose_name='Категория опухоли (врач)')),
                ('tumor_stage_ai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='scans_ai_stage', to='scans.tumorstage', verbose_name='Стадия (ai)')),
                ('tumor_stage_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='scans_doc_stage', to='scans.tumorstage', verbose_name='Стадия (врач)')),
            ],
            options={
                'verbose_name': 'Запись о снимке',
                'verbose_name_plural': 'Записи о снимках',
            },
        ),
    ]
