# Generated by Django 4.2.6 on 2024-04-05 13:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanaxis',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='scanrecord',
            name='created_datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 5, 18, 58, 29, 426269), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='scanrecord',
            name='tumor_category_ai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='scans_tumor_ai_category', to='scans.tumorcategory', verbose_name='Категория опухоли (ai)'),
        ),
        migrations.AlterField(
            model_name='tumorcategory',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tumorstage',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
    ]
