# Generated by Django 4.2.6 on 2024-04-05 16:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0002_alter_scanaxis_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanrecord',
            name='axis',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='scans_axis', to='scans.scanaxis', verbose_name='Ось'),
        ),
        migrations.AlterField(
            model_name='scanrecord',
            name='created_datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 5, 21, 5, 47, 753401), verbose_name='Дата создания'),
        ),
    ]
