# Generated by Django 4.2.9 on 2024-04-09 16:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0004_alter_scanrecord_axis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TumorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип опухоли',
                'verbose_name_plural': 'Типы опухолей',
            },
        ),
        migrations.RenameModel(
            old_name='ScanAxis',
            new_name='ScanType',
        ),
        migrations.AlterModelOptions(
            name='scantype',
            options={'verbose_name': 'Вид снимка', 'verbose_name_plural': 'Вид снимка'},
        ),
        migrations.RenameField(
            model_name='scanrecord',
            old_name='tumor_category_ai',
            new_name='mean_tumor_category_ai',
        ),
        migrations.RemoveField(
            model_name='scanrecord',
            name='axis',
        ),
        migrations.RemoveField(
            model_name='scanrecord',
            name='base_image',
        ),
        migrations.RemoveField(
            model_name='scanrecord',
            name='predicted_image',
        ),
        migrations.RemoveField(
            model_name='scanrecord',
            name='tumor_stage_ai',
        ),
        migrations.AddField(
            model_name='scanrecord',
            name='scan_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='scans_scan_type', to='scans.scantype', verbose_name='Вид снимка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scanrecord',
            name='created_datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 9, 21, 56, 22, 437092), verbose_name='Дата создания'),
        ),
        migrations.CreateModel(
            name='ScanImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_image', models.ImageField(blank=True, null=True, upload_to='scans/images/base/', verbose_name='Оригинальный снимок')),
                ('processed_image', models.ImageField(blank=True, null=True, upload_to='scans/images/predicted/', verbose_name='Предсказанный снимок')),
                ('structured_report', models.FileField(blank=True, null=True, upload_to='scans/reports/', verbose_name='DICOM-SR Отчёт')),
                ('predicted_probability', models.FloatField(default=0, verbose_name='Вероятность наличия')),
                ('tumor_category_ai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='scans_images_tumor_category', to='scans.tumorcategory', verbose_name='Категория опухоли (ai)')),
            ],
            options={
                'verbose_name': 'Снимок',
                'verbose_name_plural': 'Снимки',
            },
        ),
        migrations.AddField(
            model_name='scanrecord',
            name='scans',
            field=models.ManyToManyField(blank=True, related_name='scans_scan', to='scans.scanimage', verbose_name='Снимки'),
        ),
        migrations.AddField(
            model_name='scanrecord',
            name='tumor_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='scans_tumor_type', to='scans.tumortype', verbose_name='Область опухоли'),
            preserve_default=False,
        ),
    ]
