# Generated by Django 4.2.9 on 2024-04-12 16:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0006_alter_scanrecord_created_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='tumortype',
            name='tumor_type',
            field=models.CharField(default='', max_length=255, verbose_name='Тип'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scanrecord',
            name='created_datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 12, 21, 45, 6, 518233), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='scanrecord',
            name='scan_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='scans_scan_type', to='scans.scantype', verbose_name='Вид снимков'),
        ),
    ]
