# Generated by Django 4.2.9 on 2024-04-14 18:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0008_alter_scanrecord_created_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tumorcategory',
            name='tumor_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tumor_categories_tumor_type', to='scans.tumortype', verbose_name='Тип'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scanrecord',
            name='created_datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 14, 23, 30, 35, 435203), verbose_name='Дата создания'),
        ),
    ]
